name: Cypress Tests
on:
  push:
    branches:
      - ‘**’
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_suite: [MY, SG]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install
      # Install OpenVPN
      - name: Install OpenVPN
        run: sudo apt-get install -y openvpn
      # Save VPN Config File
      - name: Setup AWS VPN
        run: |
          echo “${{ secrets.AWS_VPN_CONFIG }}” > aws-vpn.ovpn
          echo -e “${{ secrets.AWS_VPN_USERNAME }}\n${{ secrets.AWS_VPN_PASSWORD }}” > vpn-auth.txt
          chmod 600 vpn-auth.txt  # Secure the credentials file
      # Connect to VPN using auth file
      - name: Connect to AWS VPN
        run: |
          sudo openvpn --config aws-vpn.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 10  # Allow time for VPN to connect
      - name: Verify VPN Connection
        run: curl ifconfig.me  # Confirm VPN is active
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: “cypress/e2e/${{ matrix.test_suite }}/**/*”
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.test_suite }}_screenshots
          path: cypress/screenshots